//
// Generated by OFS script hssi_ss_get_cfg.tcl using qsys-script
//

`ifndef __OFS_FIM_IP_CFG_HSSI_SS__
`define __OFS_FIM_IP_CFG_HSSI_SS__ 1

//
// The OFS_FIM_IP_CFG_<ip_name>_ETH_PORTS macro will be defined iff the
// port is active. The value does not have to be tested.
//

//
// The macros below represent the raw eth port configuration above in
// ways that are easier to process in SystemVerilog loops.
//

`define ETH_25G


`define INST_ALL_PORTS \
   `HSSI_PORT_INST(0) \
   `HSSI_PORT_INST(1) \
   `HSSI_PORT_INST(2) \
   `HSSI_PORT_INST(3) \
   `HSSI_PORT_INST(4) \
   `HSSI_PORT_INST(5) \
   `HSSI_PORT_INST(6) \
   `HSSI_PORT_INST(7) \


`define INCLUDE_HSSI_PORT_0 
`define INCLUDE_HSSI_PORT_1 
`define INCLUDE_HSSI_PORT_2 
`define INCLUDE_HSSI_PORT_3 
`define INCLUDE_HSSI_PORT_4 
`define INCLUDE_HSSI_PORT_5 
`define INCLUDE_HSSI_PORT_6 
`define INCLUDE_HSSI_PORT_7 

`define ENUM_PORT_INDEX PORT_0, PORT_1, PORT_2, PORT_3, PORT_4, PORT_5, PORT_6, PORT_7, 

// Total number of ports, not necessarily dense (see MAX_PORT_NUM)
`define OFS_FIM_IP_CFG_HSSI_SS_NUM_ETH_PORTS 8
`define OFS_FIM_IP_CFG_HSSI_SS_ETH_PACKET_WIDTH 64
`define OFS_FIM_IP_CFG_HSSI_SS_NUM_LANES 1


`endif // `ifndef __OFS_FIM_IP_CFG_HSSI_SS__
